resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: lean-soft.pull-request-diff-copy.pull-request-diff-copy-cross-platform.Pull Request Diff Copy@0
  displayName: 'Pull Request Diff Copy '

  enabled: false

- task: FtpUpload@1
  displayName: 'FTP Upload: src'
  inputs:
    serverEndpoint: 'ftp-devopshub-docs-mdwiki'

    rootDirectory: src

    remoteDirectory: /site/wwwroot/mdwiki/docs/azuredevops101/

    preservePaths: true


- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: src